USE handMeDown_db;

INSERT INTO activities(title, body, web_url, image_url, user_id)
VALUES ('San Antonio Zoo',
        'This 35-acre zoo in San Antonio, Texas has more than 3,500 animals ranging across 750 species. It’s a great day out for the whole family. You get to spend time together and also take part in many fun-filled activities. There are many behind-the-scenes interactions with animals which are sure to excite and engage the kids.',
        'https://sazoo.org/', 'https://familydestinationsguide.com/wp-content/uploads/2020/06/San-Antonio-Zoo.jpg.webp',
        2),
       ('San Antonio Aquarium',
        'The second place on our list is perfect if you’re looking for things to do in San Antonio with kids this weekend. The aquarium is the perfect indoor activity for those who love to learn a little something about underwater creatures without going on a cruise.',
        'https://sanantonioaquarium.net/',
        'https://familydestinationsguide.com/wp-content/uploads/2020/06/San-Antonio-Aquarium.jpg.webp', 2),
       ('LEGOLAND Discovery Center San Antonio',
        'This is one of the best things for kids to do in San Antonio. Also, if there is a birthday coming, you can plan a party here and that’s just unforgettable. You want to set a day aside for this because it’s not a hop in and hop out affair. You can drop off the little ones here and go check out the shops in Rivercenter in downtown San Antonio.',
        'https://www.legolanddiscoverycenter.com/san-antonio/',
        'https://familydestinationsguide.com/wp-content/uploads/2020/06/LEGOLAND-Discovery-Center-San-Antonio.jpg.webp',
        2),
       ('SeaWorld San Antonio',
        'This is a great place for close interactions with animals. You can also dive in thanks to some fantastic rides and shows. You might also witness dolphin battles and get a taste of Sesame Street.',
        'https://seaworld.com/san-antonio/',
        'https://familydestinationsguide.com/wp-content/uploads/2020/06/SeaWorld-San-Antonio.jpg.webp', 2),
       ('Morgan’s Wonderland',
        'This 25 acres of property is the world’s first completely accessible family park. There’s entertainment in the park, many accessible rides and attractions and a ton of food and gift shops to entertain folks of all ages. As of 2017, there’s also an extended version called Morgan’s Inspiration Island.',
        'https://morganswonderland.com/',
        'https://familydestinationsguide.com/wp-content/uploads/2020/06/Morgans-Wonderland.jpg.webp', 2),
       ('Six Flags Fiesta Texas',
        'From Fright Fests to Snake rides there is a gauntlet of entertainment for people of all ages. This means, it’s one of the best places to visit with family in San Antonio. You can get passes in advance which allow you to skip the line and make the best of your time here.',
        'https://www.sixflags.com/fiestatexas',
        'https://familydestinationsguide.com/wp-content/uploads/2020/06/Six-Flags-Fiesta-Texas.jpg.webp', 2),
       ('Science Mill',
        'If you like to learn using interacting sessions then this is it. This one has a little something for the whole family from exhibits to non-profit museums.',
        'https://www.sciencemill.org/',
        'https://familydestinationsguide.com/wp-content/uploads/2020/06/Science-Mill.jpg.webp', 2),
       ('Aquatica',
        'This is the world’s largest marine life park and has some unique aspects to it which make it equally fun for children and adults. There are a variety of rides, a lot of shows and some exciting encounters with animals too. And when you need to take a beat, you can head to the cabanas.',
        'https://aquatica.com/san-antonio/',
        'https://familydestinationsguide.com/wp-content/uploads/2020/06/Aquatica.jpg.webp', 2),
       ('The DoSeum',
        'The DoSeum offers hands-on experience for mom and dad and your tots. But this is where things get interesting. Here, their interactive play is designed to teach young ones and you something you’ve probably not done before. Here, kids play to learn and adults learn to play.',
        'https://www.thedoseum.org/', 'https://familydestinationsguide.com/wp-content/uploads/2020/06/The-DoSeum.jpg',
        2),
       ('Kiddie Park',
        'It’s a great place to spend the day with the kids. It is a bit old fashioned so you can sit your kids down and tell them some stories about your childhood. It’s also a treasured landmark of San Antonio.',
        'https://www.kiddiepark.com/',
        'https://familydestinationsguide.com/wp-content/uploads/2020/06/Kiddie-Park.jpg.webp', 2),
       ('Witte Museum',
        'It is situated on the banks of the San Antonio River in Brackenridge Park. This is the premier museum in San Antonio and focuses on the history, science and water resources of south Texas.',
        'https://www.wittemuseum.org/',
        'https://familydestinationsguide.com/wp-content/uploads/2020/06/Witte-Museum.jpg.webp', 2),
       ('Graff 7A Ranch / South Texas Maize',
        'It’s a fifth-generation farm and ranch with a flagship fall corn maze event from mid-September to late November. And it’s just a short ride from San Antonio. That alone is a great reason to take the kids.',
        'https://graff7aranch.com/',
        'https://familydestinationsguide.com/wp-content/uploads/2020/06/Graff-7A-Ranch-South-Texas-Maize.jpg.webp', 2),
       ('Altitude Trampoline Park',
        'You can get a pass or make it a one-time thing. Either way, this is a great destination if you’re looking for fun things to do with family in San Antonio. From birthday parties to group events, there’s something on the stage here all through the year.',
        'https://www.altitudesa.com/',
        'https://familydestinationsguide.com/wp-content/uploads/2020/06/Altitude-Trampoline-Park.jpg.webp', 2),
       ('San Antonio River Walk', 'The River Walk doesn’t need a whole day but you want to spend as much time as possible here. There’s parades, festivals, museums and many shopping opportunities here.

', 'https://www.thesanantonioriverwalk.com/',
        'https://familydestinationsguide.com/wp-content/uploads/2020/06/San-Antonio-River-Walk.jpg.webp', 2),
       ('Natural Bridge Caverns',
        'If you like the idea of adventure which is almost 200 feet below the surface of the earth, this is it. You can avail the guided tour for the whole family and explore some incredible formations. This one is more than just a cave. You’ll see.',
        'https://naturalbridgecaverns.com/',
        'https://familydestinationsguide.com/wp-content/uploads/2020/06/Natural-Bridge-Caverns.jpg.webp', 2),
       ('San Antonio Botanical Garden',
        'It’s a garden spread over 38 acres and can be explored in whichever way you see fit. There’s no rigid structure. Out of that, 2.5 acres is a garden design that is meant to immerse you into nature. It’s a great place to teach kids the value of plants in our ecosystem.',
        'https://www.sabot.org/',
        'https://familydestinationsguide.com/wp-content/uploads/2020/06/San-Antonio-Botanical-Garden.jpg.webp', 2),
       ('The Alamo',
        'If you like to see dressed-up characters talk about guns and life in the Alamo, this is the place to be. That’s an important chapter in the history of the great state of Texas. It was originally called the Misión San Antonio de Valero and it’s a Spanish mission with a fortress compound.',
        'https://www.thealamo.org/',
        'https://familydestinationsguide.com/wp-content/uploads/2020/06/The-Alamo.jpg.webp', 2),
       ('iFly San Antonio',
        'Conquering the skies, well, through skydiving is different everywhere and should definitely top the unique stuff to do with kids list. This one is indoors in a wind tunnel and the place to try it when you’re in San Antonio.',
        'https://www.iflyworld.com/san-antonio/',
        'https://familydestinationsguide.com/wp-content/uploads/2020/06/iFly-San-Antonio.jpg.webp', 2);



